/**
 * @typedef {object} Product
 * @property {string} id
 * @property {object} content
 * @property {object[]} content.product_benefits
 * @property {string} content.product_benefits.icon
 * @property {string} content.product_benefits.text
 * @property {boolean} content.enable_quantity
 * @property {number} content.max_quantity
 * @property {number} content.up_sell_cols
 * @property {string} currency
 * @property {string} description
 * @property {boolean} bundle
 * @property {object[]} images
 * @property {string} images.id
 * @property {object} images.file
 * @property {number} images.file.height
 * @property {string} images.file.md5
 * @property {string} images.file.url
 * @property {number} images.file.width
 * @property {string} name
 * @property {object[]} options
 * @property {string} options.id
 * @property {object[]} options.values
 * @property {string} options.values.id
 * @property {string} options.values.name
 * @property {null|number} options.values.price
 * @property {null} options.values.shipment_weight
 * @property {null} options.values.description
 * @property {string} options.name
 * @property {boolean} options.active
 * @property {string} options.input_type
 * @property {boolean} options.variant
 * @property {null} options.description
 * @property {boolean} options.required
 * @property {string} options.attribute_id
 * @property {number} price
 * @property {string} sku
 * @property {string} slug
 * @property {null} stock_status
 * @property {boolean} stock_tracking
 * @property {boolean} stock_purchasable
 * @property {object} attributes
 * @property {object} attributes.brand
 * @property {string} attributes.brand.name
 * @property {string} attributes.brand.type
 * @property {boolean} attributes.brand.visible
 * @property {boolean} attributes.brand.filterable
 * @property {string} attributes.brand.id
 * @property {string} attributes.brand.value
 * @property {} tags
 * @property {null} meta_title
 * @property {string} meta_description
 * @property {object} variants
 * @property {number} variants.count
 * @property {object[]} variants.results
 * @property {string} variants.results.id
 * @property {string} variants.results.currency
 * @property {object[]} variants.results.images
 * @property {string} variants.results.images.id
 * @property {object} variants.results.images.file
 * @property {number} variants.results.images.file.height
 * @property {string} variants.results.images.file.md5
 * @property {string} variants.results.images.file.url
 * @property {number} variants.results.images.file.width
 * @property {string} variants.results.name
 * @property {string[]} variants.results.option_value_ids
 * @property {number} variants.results.price
 * @property {string} variants.results.sku
 * @property {null} variants.results.stock_status
 * @property {number} variants.page
 * @property {boolean} sale
 */

export default {};
