export const defaultFormState = {
  firstName: "",
  lastName: "",
  nickName: "",
  email: "",
  phone: "",
  discord: "",
  reddit: "",
  instagram: "",
  address1: "",
  address2: "",
  city: "",
  zip: "",
  country: "CZ",
};
